sudo: required

language: python

services:
  - docker

before_install:

script:
  - docker-compose --version
  - docker --version
  - ./run-tests.sh

notifications:
    email: false

after_success:
  - test $PYTHON_VERSION = "3.8" && pip install coveralls && coveralls

jobs:
  include:
  - python: "2.7.17"
    env: PYTHON_VERSION=2.7.17
  - python: "3.7"
    env: PYTHON_VERSION=3.7
  - python: "3.8"
    env: PYTHON_VERSION=3.8

deploy:
  provider: pypi
  user: thorgate
  password:
    secure: >
      cfDtspUHU3Q5V6Dl2LhxEs5gCsB/f16yWKP2ibwKFuqGD323O6Pk3UAlGIBk+c+M9ebsYnftq2IjOkJnVpfCRYLnwM0QmHCzNNKwXHhTSAy9p
      C0BJhRP/JPd6SqopnLz/GrqY3cb0Z6dMvq2NXtcG3DBX4YgRnXuoZlH7YBgz5BwJm2p1ueP99v45hP0Qnlm8frEyhzjMufZN5QtCVlr045902
      Uk7IX497JntXM00pzXN8ODZOEeHCMcSMaKaT5Yib1v2QTibpcBwfLhqXmx1RKCODLKZNdyWMxqeKt5FemY6TMo4dPz7JuGOyTwH4SUEAGf8ls
      DOQdmUCutqWdcI6bBNkaZ1eZ2WYv17iUHq5sp9IRWiznyP2y9q97pbtZILCCzfdi0XIZbd/Bp4UwPsaCJJG7oPSfKdmjbGi77+RLNTXI9NUYE
      zML4+Dp/72WrrHhfM5Z0ut6nsBLN6dUUizsIw41cYm8ZoOiH4MXZx2AHmqo1/94BuVymBabU3Znk8eqQQXIRjMvhuoKS6GTrAELgRVQruQ91E
      QxIk+w8uCbpGDutFeMy9LLfdWDYcK7TBqyzJ4+zSZq/Rzr+nsN4rvlgxplW6swBa9yr93COAofr4FxF0c+luE5SoSFtQe2x9TqeXHCPxljTKM
      kIr4U7jhTcnf7JGxK4xFbLju1IEKg=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: thorgate/tg-hammer
    python: "3.8"
