# Docker-compose configuration for hammer-time

version: '2'

services:
    master:
        container_name: tghammer_master
        build:
            context: .
            dockerfile: Dockerfile-master-rendered
        entrypoint: /hammer/docker-entrypoint-master.sh
        networks:
            hammer:
                aliases:
                    - hammer.repo.host
        depends_on:
            - slave

    slave:
        container_name: tghammer_slave
        build:
            context: .
            dockerfile: Dockerfile-slave-rendered
        entrypoint: /hammer/docker-entrypoint-slave.sh
        networks:
            hammer:
                aliases:
                    - staging.hammer

networks:
    hammer:
