# Dockerfile for slave machine

FROM python:[PYTHON_VERSION]

##############   Install system requirements   #################
RUN apt-get update
RUN apt-get install -y software-properties-common
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys F59CE3A8323293EE
RUN add-apt-repository -y ppa:mercurial-ppa/releases/
RUN sed -i 's/focal/xenial/' /etc/apt/sources.list.d/mercurial-ppa-ubuntu-releases-focal.list || echo "not needed on py2"
RUN sed -i 's/jessie/wily/' /etc/apt/sources.list.d/mercurial-ppa-releases-jessie.list || echo "not needed on py3"
RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install -y --no-install-recommends g++ sudo build-essential git mercurial openssh-server
RUN rm -rf /var/lib/apt/lists/*


##############   Add SSH keys   #################
COPY ./tests/ssh /root/.ssh
RUN chmod 700 -R /root/.ssh
RUN grep -q -F 'RSAAuthentication yes' /etc/ssh/sshd_config || echo 'RSAAuthentication yes' >> /etc/ssh/sshd_config
RUN grep -q -F 'PubkeyAuthentication yes' /etc/ssh/sshd_config || echo 'PubkeyAuthentication yes' >> /etc/ssh/sshd_config
RUN grep -q -F 'StrictHostKeyChecking no' /etc/ssh/ssh_config || echo 'StrictHostKeyChecking no' >> /etc/ssh/ssh_config
RUN grep -q -F 'NoHostAuthenticationForLocalhost yes' /etc/ssh/ssh_config || echo 'NoHostAuthenticationForLocalhost yes' >> /etc/ssh/ssh_config
RUN echo `cat /root/.ssh/test_key.pub` >> /root/.ssh/authorized_keys
RUN echo "Host hammer.repo.host" >> /root/.ssh/config
RUN echo "    User root" >> /root/.ssh/config
RUN echo "    IdentityFile /root/.ssh/test_key" >> /root/.ssh/config


##############   Make project root   #################
RUN mkdir -p /srv
RUN chmod 7777 -R /srv/


##############   Add entry point script   #################
COPY ./docker-entrypoint-slave.sh /hammer/docker-entrypoint-slave.sh
